#! /bin/bash

ROOT=$(pwd)
echo $ROOT

TYPE=Debug

git submodule update --init --recursive

# TODO: Do this in the cmake file?

# build gflags if binary folder does not exist
if [ ! -d "$ROOT/build_cmake/third_party/gflags"  ]; then
    mkdir -p $ROOT/build_cmake/third_party/gflags
    cd $ROOT/build_cmake/third_party/gflags
    
    cmake  -DCMAKE_DEBUG_POSTFIX="" -DBUILD_SHARED_LIBS=ON -DINSTALL_LIBS=ON -DCMAKE_BUILD_TYPE=$TYPE -DCMAKE_INSTALL_PREFIX:PATH=$ROOT/build_cmake/third_party/gflags $ROOT/third_party/gflags
    make -j4
    make install
fi

# build flatbuffers if binary folder does not exist
if [ ! -d "$ROOT/build_cmake/third_party/flatbuffers"  ]; then
    mkdir -p $ROOT/build_cmake/third_party/flatbuffers
    cd $ROOT/build_cmake/third_party/flatbuffers
    
    cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$TYPE -DCMAKE_INSTALL_PREFIX:PATH=$ROOT/build_cmake/third_party/flatbuffers $ROOT/third_party/flatbuffers
    make -j4 all
fi

cd $ROOT/core/fbs/schemas
$ROOT/build_cmake/third_party/flatbuffers/flatc --cpp --gen-mutable -o ../  *

cd $ROOT/build_cmake

cmake -DCMAKE_BUILD_TYPE=$TYPE ..
make -j4

cd $ROOT/build_cmake/test
ctest
